run1:
	g++ -std=c++11 -fopenmp task1.cpp -o bin/pg1
	./bin/pg1

run2:
	g++ -std=c++11 -fopenmp task2.1.cpp -o bin/pg2.1
	g++ -std=c++11 -fopenmp task2.2.cpp -o bin/pg2.2
	./bin/pg2.1
	./bin/pg2.2

run4:
	g++ -std=c++11 -fopenmp task4.1.cpp -o bin/pg4.1
	g++ -std=c++11 -fopenmp task4.2.cpp -o bin/pg4.2
	./bin/pg4.1
	./bin/pg4.2

run5:
	g++ -std=c++11 -fopenmp task5.1.cpp -o bin/pg5.1
	g++ -std=c++11 -fopenmp task5.2.cpp -o bin/pg5.2
	g++ -std=c++11 -fopenmp task5.3.cpp -o bin/pg5.3
	./bin/pg5.1
	./bin/pg5.2
	./bin/pg5.3

clean:
	rm task*
