run1.1:
	g++ -std=c++17 -O2 -Wall -Wextra -pthread t1.1.cpp -o bin/t1.1
	./bin/t1.1

run1.2:
	g++ -std=c++20 -O2 -Wall -Wextra -pthread t1.2.cpp -o bin/t1.2
	./bin/t1.2

run2:
	g++ -std=c++20 -O2 -Wall -Wextra -pthread t2.cpp -o bin/t2
	./bin/t2