FROM python:3.11

RUN apt-get update \
    && apt-get install -y gcc

COPY requirements.txt /app/

RUN pip install -r /app/requirements.txt

COPY . /app/

WORKDIR /app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0"]