run1:
	g++ -std=c++17 -O2 -pthread t1.cpp -o bin/t1
	./bin/t1


run2:
	g++ -std=c++17 -O2 -pthread t2.cpp -o bin/t2
	./bin/t2

run3:
	g++ -std=c++17 -O2 -pthread t3.cpp -o bin/t3
	./bin/t3

run4:
	g++ -std=c++17 -O2 -pthread -fopenmp t4.cpp -o bin/t4
	./bin/t4