services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.6-management-alpine
    hostname: my-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq/mnesia"
    ports:
      - 5672:5672
      - 15672:15672
