services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sql_server_container
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Your_password123
            - MSSQL_PID=Express
            - MSSQL_AGENT_ENABLED=false
        ports:
            - "1433:1433"
        volumes:
            - mssql-data:/var/opt/mssql
        restart: unless-stopped

volumes:
    mssql-data:
