global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dice-cluster'
    environment: 'production'

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'dice-server'
  
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']