CPP_FILE = cpp/solve1.cpp
CPP_OUTPUT = cpp/solve

PYTHON_FILE = task5.py

CXX = g++

all: help

run_cpp: 
	$(CXX) -o $(CPP_OUTPUT) $(CPP_FILE)
	./$(CPP_OUTPUT)

python: $(PYTHON_FILE)
	python $(PYTHON_FILE)